// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoRFK5IVeRV6C211I92f3XPdxY8SdZLIw',
    appId: '1:514360619678:web:c9f41e2d7c52c0170dc18f',
    messagingSenderId: '514360619678',
    projectId: 'partypal-b9513',
    authDomain: 'partypal-b9513.firebaseapp.com',
    storageBucket: 'partypal-b9513.firebasestorage.app',
    measurementId: 'G-BY0JM5HLKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEnbLCFk6rFnu0YV3MGRVWDNmulfUTymo',
    appId: '1:514360619678:android:76bf0c98fd0f43270dc18f',
    messagingSenderId: '514360619678',
    projectId: 'partypal-b9513',
    storageBucket: 'partypal-b9513.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-tPd5Y_nZVOy3MOKjMFsHM7imfDHoALE',
    appId: '1:514360619678:ios:036b5ab316649feb0dc18f',
    messagingSenderId: '514360619678',
    projectId: 'partypal-b9513',
    storageBucket: 'partypal-b9513.firebasestorage.app',
    iosBundleId: 'com.amaronetto.festafacil',
  );
}
